from enum import Enum

Mutation = Enum('Mutation', ['NONE', 'SOLDIER', 'CALLER','S_MASTER', 'WINNER', 'PARROT', 'GERUDO', 'CROOK', 'FARMER', 'BOMBER', 'MINER', 'KAMIKAZE', "CHINA"]) # 6

MutationOrder = ["GERUDO", "SMASTER", "CALLER", "KAMIKAZE","MINER" ,"FARMER", "CROOK","GERUDO", "CROOK", "KAMIKAZE", "CHINA","WINNER", "WINNER","WINNER","WINNER","WINNER","WINNER","WINNER", "PARROT"]
#14
RandomMutation = ["SMASTER", "KAMIKAZE", "KAMIKAZE", "KAMIKAZE", "KAMIKAZE", "KAMIKAZE", "KAMIKAZE", "KAMIKAZE", "FARMER", "GERUDO", "KAMIKAZE", "KAMIKAZE", "MINER", "CROOK"]
